name = "Dart"
uuid = "72985ce2-e41e-4ea6-a632-93a0cf99369d"
authors = ["matthias-michalek <matthiasmichalek@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
